project_name: dpx

before:
  hooks:
    - go mod tidy

builds:
  - <<: &build_defaults
      binary: dpx
      main: ./cmd/dpx
      ldflags:
        - -s -w -X github.com/dpx/dpx/pkg/version.Version={{.Version}}
    id: macos
    goos: [darwin]
    goarch: [amd64, arm64]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [386, arm, amd64, arm64]
    env:
      - CGO_ENABLED=0

archives:
  - replacements:
      darwin: macOS
      linux: linux
      windows: Windows
      amd64: x86_64
    wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - tap:
      owner: dpx
      name: homebrew-dpx
    commit_author:
      name: rezigned
    homepage: https://github.com/dpx/dpx
    description: Run any executable inside container on your machine
    install: |
      bin.install "dpx"
